services:
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sorah_travel_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "20007:80"
    volumes:
      - ./:/var/www
      - /var/www/sorah-travel.devtechnosys.tech/public_html/public/uploads:/var/www/public/uploads